# Generated by Django 2.2.10 on 2020-03-27 12:51

import django.core.validators
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplate',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1900), products.models.max_value_current_year]),
        ),
    ]
