# Generated by Django 2.2.10 on 2020-03-27 12:55

import django.core.validators
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200327_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproduct',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productproduct',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='manufacturer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='style',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1960), products.models.max_value_current_year]),
        ),
    ]
